{{- if .Values.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ default .Release.Name .Values.configMap.name }}
  namespace: {{ default .Release.Namespace .Values.configMap.namespace }}
container:
    image: {{ default .Release.Name .Values.configMap.container.image }}
    tag: {{ default "latest" .Values.configMap.container.tag }}
spec:
  data:
    {{- range .Values.configMap.data }}
    {{ .key }}: {{ .value | quote }}
    {{- end }}
{{- end }}
