version: 2

dist: ./bin

builds:
  - id: service1
    binary: service1-{{ .Os }}-{{ .Arch }}
    main: ./service1/cmd/server
    env:
      - CGO_ENABLED=0
    goos: [linux]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X gh-actions/internal/version.Version={{ .Version }}
      - -X gh-actions/internal/version.GitCommit={{ .Commit }}
    no_unique_dist_dir: true

  - id: service2
    binary: service2-{{ .Os }}-{{ .Arch }}
    main: ./service2/cmd/server
    env:
      - CGO_ENABLED=0
    goos: [linux]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X gh-actions/internal/version.Version={{ .Version }}
      - -X gh-actions/internal/version.GitCommit={{ .Commit }}
    no_unique_dist_dir: true

snapshot:
  version_template: "{{ .Version }}"

archives:
  - formats: [binary]
    name_template: "{{ .Binary }}"
    strip_binary_directory: true

dockers:
  # service1
  - image_templates:
      - "{{ .Env.REGISTRY }}/{{ .Env.REPOSITORY }}/service1:latest"
      - "{{ .Env.REGISTRY }}/{{ .Env.REPOSITORY }}/service1:{{ .Version }}"
      - "{{ .Env.REGISTRY }}/{{ .Env.REPOSITORY }}/service1:{{ .FullCommit }}"
    dockerfile: ./deploy/docker/Dockerfile.prod
    use: buildx
    build_flag_templates:
      - "--push"
      - "--platform=linux/amd64,linux/arm64"
      - "--build-arg=SERVICE=service1"
      
  # service2
  - image_templates:
      - "{{ .Env.REGISTRY }}/{{ .Env.REPOSITORY }}/service2:latest"
      - "{{ .Env.REGISTRY }}/{{ .Env.REPOSITORY }}/service2:{{ .Version }}"
      - "{{ .Env.REGISTRY }}/{{ .Env.REPOSITORY }}/service2:{{ .FullCommit }}"
    dockerfile: ./deploy/docker/Dockerfile.prod
    use: buildx
    build_flag_templates:
      - "--push"
      - "--platform=linux/amd64,linux/arm64"
      - "--build-arg=SERVICE=service2"

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
  filters:
    exclude:
      - "^test:"
      - "^ci:"
      - "^chore:"
