name: 'Wait for Workflow'
description: 'Wait for another workflow to complete that is running on the same commit SHA'
inputs:
  workflow-name:
    description: 'Name of the workflow to wait for'
    required: true
  github-token:
    description: 'GitHub token with permissions to check workflow runs'
    required: true
    default: ${{ github.token }}
  timeout-minutes:
    description: 'Maximum time to wait in minutes'
    required: false
    default: '5'
  poll-interval:
    description: 'Time in seconds between status checks'
    required: false
    default: '20'

runs:
  using: 'composite'
  steps:
    - name: Wait for workflow to complete
      shell: bash
      run: ${{ github.action_path }}/wait-for-workflow.sh
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        WORKFLOW_NAME: ${{ inputs.workflow-name }}
        TIMEOUT_MINUTES: ${{ inputs.timeout-minutes }}
        POLL_INTERVAL: ${{ inputs.poll-interval }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_SHA: ${{ github.sha }} 