name: CI

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  skip-if-pr:
    name: Cancel if PR exists
    runs-on: ubuntu-latest
    outputs:
      pr-number: ${{ steps.find-pr.outputs.number }}
    steps:
      - uses: jwalton/gh-find-current-pr@master
        id: find-pr
        with:
          state: open

      - uses: action-pack/cancel@v1
        if: ${{ steps.find-pr.outputs.number != '' }}

  tests:
    name: Test & Lint
    permissions:
      pull-requests: read
      contents: read
      checks: write
    uses: ./.github/workflows/tests.yaml
    needs: skip-if-pr