name: CI

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  get-pr:
    name: Get PR
    runs-on: ubuntu-latest
    outputs:
      pr-number: ${{ steps.find-pr.outputs.number }}
    steps:
      - uses: jwalton/gh-find-current-pr@master
        id: find-pr
        with:
          state: open

  tests:
    name: Test & Lint
    permissions:
      pull-requests: read
      contents: read
      checks: write
    uses: ./.github/workflows/tests.yaml
    needs: get-pr
    if: ${{ needs.get-pr.outputs.pr-number == '' }}
