name: Main

on:
  push:
    branches: [ main ]

jobs:
  test-lint-build:
    permissions:
      pull-requests: read
      checks: write
      contents: read
    uses: ./.github/workflows/pull_request.yaml

  release:
    name: Release
    permissions:
      id-token: write
      contents: read
    needs: test-lint-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: ghactions-${{ matrix.arch }}

      - name: Load Docker Image
        run: docker load -i ghactions-${{ matrix.arch }}.tar

      - name: Push Docker Image
        run: |
          docker tag ghactions:${{ matrix.arch }} ghactions:${{ github.sha }}
          echo "Pushing ghactions:${{ matrix.arch }}"

  release-docker-manifest:
    name: Release Docker Manifest
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Create And Push Manifest
        run: |
          echo "Pushing ghactions:latest manifest"
  
  deploy:
    name: Deploy
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo "Deploying ghactions:latest"