name: Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/tests.yaml

  build:
    name: Build
    needs: tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - service1
          - service2
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean --snapshot
          workdir: ${{ matrix.service }}
        env:
          IMAGE_REPOSITORY: gh-actions
