name: Pull Request

on:
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Wait for CI workflow to complete
        uses: ./.github/actions/wait-for-workflow
        with:
          workflow-name: CI
          github-token: ${{ secrets.GITHUB_TOKEN }}
          timeout-minutes: 5
          poll-interval: 20

  build:
    name: Build
    needs: ci
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
          cache-dependency-path: |
            go.sum

      - name: Build Go Binary
        run: |
          mkdir -p bin
          GOOS=linux GOARCH=${{ matrix.arch }} go build -o ./bin/ghactions-${{ matrix.arch }} ./cmd/server/main.go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./bin
          file: ./Dockerfile
          push: false
          outputs: type=docker,dest=ghactions-${{ matrix.arch }}.tar
          platforms: linux/${{ matrix.arch }}
          tags: ghactions:${{ matrix.arch }}
          build-args: |
            SERVICE=ghactions-${{ matrix.arch }}

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'push' }}
        with:
          name: ghactions-${{ matrix.arch }}
          path: ./ghactions-${{ matrix.arch }}.tar
          if-no-files-found: error
          retention-days: 1
          compression-level: 0
          overwrite: true
