name: Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/tests.yaml

  build:
    name: Build
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          install-only: true
          version: v2.8.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build Snapshot
        run: goreleaser release --clean --snapshot
        env:
          IMAGE_REPOSITORY: gh-actions
