name: Pull Request

on:
  pull_request:
    branches: [main]
  workflow_call:
    inputs:
      push:
        required: false
        type: boolean
        default: true

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml

  next-version:
    runs-on: ubuntu-latest
    outputs:
      next-version: ${{ steps.next-version.outputs.next-version || 'pr' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Get Next Version
        id: next-version
        run: |
          npx -p @semantic-release/commit-analyzer semantic-release --dry-run --no-ci --plugins "@semantic-release/commit-analyzer"

          NEXT_VERSION=$(npx -p @semantic-release/commit-analyzer semantic-release --dry-run --no-ci --plugins "@semantic-release/commit-analyzer" \
            | grep -o "next release version is [0-9]\+\.[0-9]\+\.[0-9]\+" \
            | sed 's/next release version is //')
          echo "next-version=$NEXT_VERSION" >> $GITHUB_OUTPUT

  build-binary:
    name: Build Binary
    needs: [tests, next-version]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ghactions]
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
          cache-dependency-path: |
            go.sum

      - name: Build Go Binary
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=${{ matrix.arch }} go build \
            -o bin/${{ matrix.service }}-${{ matrix.arch }} \
            -ldflags="-s -w" \
            -ldflags="-X 'gh-actions/internal/version.Version=${{ needs.next-version.outputs.next-version }}'" \
            -ldflags="-X 'gh-actions/internal/version.GitCommit=${{ github.sha }}'" \
            ./${{ matrix.service }}/cmd/server/main.go

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.service }}-${{ matrix.arch }}
          path: bin/${{ matrix.service }}-${{ matrix.arch }}
          if-no-files-found: error
          retention-days: 1
          compression-level: 0
          overwrite: true

  build-push-docker-images:
    name: Build and Push Docker Image
    needs: [tests, next-version, build-binary]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ghactions]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
          cache-dependency-path: |
            go.sum

      - name: Download Binaries
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ matrix.service }}-*
          path: bin
          merge-multiple: true

      - name: Authenticate to GCP Registry
        if: ${{ inputs.push }}
        run: |
          echo "Authenticating to GCP Registry"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Metadata
        id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.service }}
          tags: |
            type=sha
            type=raw,value=latest
            type=raw,value=${{ needs.next-version.outputs.next-version }}

      - name: Build Docker Image
        run: |
          echo "Building Docker Image"

      # - name: Build Docker Image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: ./bin
      #     file: ./deploy/docker/Dockerfile.prod
      #     outputs: type=${{ inputs.push == true && 'registry' || 'oci' }}
      #     platforms: linux/arm64,linux/amd64
      #     tags: ${{ steps.docker-metadata.outputs.tags }}
      #     labels: ${{ steps.docker-metadata.outputs.labels }}
      #     build-args: |
      #       SERVICE=${{ matrix.service }}
