name: Pull Request

on:
  pull_request:
    branches: [main]
  workflow_call:
    inputs:
      push:
        required: false
        type: boolean
        default: true

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml

  build-binaries:
    needs: tests
    uses: ./.github/workflows/build-binaries.yaml

  build-push-docker-images:
    name: Build and Push Docker Image
    needs: [tests, build-binaries]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ghactions]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
          cache-dependency-path: |
            go.sum

      - name: Download ARM64 Binary
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.service }}-arm64
          path: ${{ matrix.service }}-arm64

      - name: Download AMD64 Binary
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.service }}-amd64
          path: ${{ matrix.service }}-amd64

      - name: Authenticate to GCP Registry
        if: ${{ inputs.push }}
        run: |
          echo "Authenticating to GCP Registry"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./bin
          file: ./deploy/docker/Dockerfile.prod
          outputs: type=${{ inputs.push == true && 'registry' || 'oci' }}
          platforms: linux/arm64,linux/amd64
          tags: ${{ matrix.service }}:latest
          build-args: |
            SERVICE=${{ matrix.service }}
